name: Taskinator

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Build Gem
      run: rake build
    - name: Run tests
      run: rake spec

  publish:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release Gem
      uses: discourse/publish-rubygems-action@v2
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        GIT_NAME: Chris Stefano
        GIT_EMAIL: virtualstaticvoid@gmail.com
